### ISSUE TITLE
The Following Error is Generated

### ISSUE THREAD

**Issue by ankitgurung** [akanyaani/gpt-2-tensorflow2.0#13]
DESKTOP-NSQNAPV:~/ai/gpt-2-tensorflow2.0$ pip3 install -r requirements.txt
Collecting setuptools==41.0.1
  Using cached setuptools-41.0.1-py2.py3-none-any.whl (575 kB)
Collecting ftfy==5.6
  Using cached ftfy-5.6.tar.gz (58 kB)
Collecting tqdm==4.32.1
  Using cached tqdm-4.32.1-py2.py3-none-any.whl (49 kB)
Requirement already satisfied: Click==7.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 4)) (7.0)
Collecting sentencepiece==0.1.83
  Using cached sentencepiece-0.1.83.tar.gz (497 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-zv127a6c/sentencepiece/setup.py'"'"'; __file__='"'"'/tmp/pip-install-zv127a6c/sentencepiece/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-zv127a6c/sentencepiece/pip-egg-info
         cwd: /tmp/pip-install-zv127a6c/sentencepiece/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-zv127a6c/sentencepiece/setup.py", line 29, in <module>
        with codecs.open(os.path.join('..', 'VERSION'), 'r', 'utf-8') as f:
      File "/usr/lib/python3.8/codecs.py", line 905, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '../VERSION'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
DESKTOP-NSQNAPV:~/ai/gpt-2-tensorflow2.0$

**Comment by ActiveNick** [comment]
I'm getting the same error. What was your fix?
