### ISSUE TITLE
python setup.py egg_info did not run successfully.

### ISSUE THREAD

**Issue by XiaonGitHub** [akanyaani/gpt-2-tensorflow2.0#31]
I'm a complete beginner in coding, so I'm lost in what to do. 
I've been following the readme and during setup, when I write in anaconda prompt,` pip install -r requirements.txt`, 
I get the error: 

`Collecting sentencepiece==0.1.83
  Using cached sentencepiece-0.1.83.tar.gz (497 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\ryyuj\AppData\Local\Temp\pip-install-1j97ilvg\sentencepiece_23e331750cc749e6b09f5118d946390c\setup.py", line 29, in <module>
          with codecs.open(os.path.join('..', 'VERSION'), 'r', 'utf-8') as f:
        File "C:\Users\ryyuj\anaconda3\lib\codecs.py", line 905, in open
          file = builtins.open(filename, mode, buffering)
      FileNotFoundError: [Errno 2] No such file or directory: '..\\VERSION'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

Any ideas on what the problem might be, and what to do about it?
Thank you so much!

**Comment by khatchad** [comment]
Try `sentencepiece==0.2.0`.
